AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  first-lamda

  Sample SAM Template for first-lamda


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::getContext
      Runtime: java8
      MemorySize: 512
      Timeout: 6
      Environment:
       Variables:
           google: https://stackoverflow.com/questions/44707574/springboot-fully-executable-jar-without-dependencies-inside