server:
  port: 8761 
#default 8761 then no need to add  
spring:
  application:
    name: Eureka-Serever  
    
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka  
  server:
    wait-time-in-ms-when-sync-empty: 0 
