package com.arun.controllers;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class RestControllete {

	@GetMapping("/getManyData")
	public Object getManyData() {
		return "[{\r\n"
				+ "  \"id\": 1,\r\n"
				+ "  \"first_name\": \"Chip\",\r\n"
				+ "  \"last_name\": \"Cressingham\",\r\n"
				+ "  \"email\": \"ccressingham0@boston.com\",\r\n"
				+ "  \"gender\": \"Bigender\",\r\n"
				+ "  \"ip_address\": \"146.221.212.240\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 2,\r\n"
				+ "  \"first_name\": \"Tad\",\r\n"
				+ "  \"last_name\": \"Simonel\",\r\n"
				+ "  \"email\": \"tsimonel1@amazon.co.uk\",\r\n"
				+ "  \"gender\": \"Bigender\",\r\n"
				+ "  \"ip_address\": \"104.199.40.100\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 3,\r\n"
				+ "  \"first_name\": \"Aubry\",\r\n"
				+ "  \"last_name\": \"Corbin\",\r\n"
				+ "  \"email\": \"acorbin2@latimes.com\",\r\n"
				+ "  \"gender\": \"Agender\",\r\n"
				+ "  \"ip_address\": \"32.15.97.105\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 4,\r\n"
				+ "  \"first_name\": \"Al\",\r\n"
				+ "  \"last_name\": \"Burkart\",\r\n"
				+ "  \"email\": \"aburkart3@instagram.com\",\r\n"
				+ "  \"gender\": \"Female\",\r\n"
				+ "  \"ip_address\": \"221.203.21.39\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 5,\r\n"
				+ "  \"first_name\": \"Tamra\",\r\n"
				+ "  \"last_name\": \"Oles\",\r\n"
				+ "  \"email\": \"toles4@psu.edu\",\r\n"
				+ "  \"gender\": \"Bigender\",\r\n"
				+ "  \"ip_address\": \"177.104.41.73\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 6,\r\n"
				+ "  \"first_name\": \"Ermina\",\r\n"
				+ "  \"last_name\": \"Burford\",\r\n"
				+ "  \"email\": \"eburford5@storify.com\",\r\n"
				+ "  \"gender\": \"Male\",\r\n"
				+ "  \"ip_address\": \"188.201.124.69\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 7,\r\n"
				+ "  \"first_name\": \"Dasha\",\r\n"
				+ "  \"last_name\": \"Ferrero\",\r\n"
				+ "  \"email\": \"dferrero6@nih.gov\",\r\n"
				+ "  \"gender\": \"Male\",\r\n"
				+ "  \"ip_address\": \"25.231.145.194\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 8,\r\n"
				+ "  \"first_name\": \"Tamarah\",\r\n"
				+ "  \"last_name\": \"Millea\",\r\n"
				+ "  \"email\": \"tmillea7@who.int\",\r\n"
				+ "  \"gender\": \"Genderfluid\",\r\n"
				+ "  \"ip_address\": \"226.240.17.21\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 9,\r\n"
				+ "  \"first_name\": \"Findley\",\r\n"
				+ "  \"last_name\": \"Samuels\",\r\n"
				+ "  \"email\": \"fsamuels8@jiathis.com\",\r\n"
				+ "  \"gender\": \"Male\",\r\n"
				+ "  \"ip_address\": \"87.223.250.0\"\r\n"
				+ "}, {\r\n"
				+ "  \"id\": 10,\r\n"
				+ "  \"first_name\": \"August\",\r\n"
				+ "  \"last_name\": \"Signoret\",\r\n"
				+ "  \"email\": \"asignoret9@behance.net\",\r\n"
				+ "  \"gender\": \"Agender\",\r\n"
				+ "  \"ip_address\": \"249.139.191.212\"\r\n"
				+ "}]";
	}
	
}
